<?php

namespace App\Modules\Admin\User\Requests;
use App\Modules\Admin\Heroes\Models\Heroes;
use \Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rule;

class UpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        if (Auth::user()->role('admin') || Auth::user()->role('super_admin')) {
            return true;
        }
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'name' => 'nullable | max:50',
            'password' => 'nullable',
            'hero_id' => [
                'nullable',
                Rule::exists('heroes','id')
            ]
        ];
    }

    public function validated($key = null, $default = null)
    {
        $data =  parent::validated($key, $default); // TODO: Change the autogenerated stub

        $data['password'] = Hash::make($data['password']);


        return $data;
    }
}
