<?php

namespace App\Modules\Admin\HackSkills\Requests;
use App\Modules\Admin\Heroes\Models\Heroes;
use \Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class HackSkillsStoreRequest extends  FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        if (Auth::user()->role('admin') || Auth::user()->role('super_admin')) {
            return true;
        } else {
            dd('Вы не Админ');
        }
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'name' => 'nullable | max:50',
            'rarity' => 'in:Уникальный,Редкий,Уникальный,Сверхъуникальный'
        ];
    }

    public function validated($key = null, $default = null)
    {
        $data =  parent::validated($key, $default); // TODO: Change the autogenerated stub



        return $data;
    }

}
